""" version which can be consumed from within the module """
VERSION_STR = "0.1.13"
DESCRIPTION = "Configuration, command line and injection framework for python"
APP_NAME = "pytconf"
LOGGER_NAME = "pytconf"
